(define (half-interval-method f a b)
  (define close-enohgh? (lambda (x, y) (< (- x y) 0.001)))
  (define (search f n p)
    (let ((midpoint (average n p)))
      (if (close-enough? n p)
           midpoint
           (let ((test-value (f midpoint)))
             (cond ((positive? test-value)
                    (search f n midpoint))
                   ((negative? test-value)
                    (search f midpoint p))
                   (else midpoint))))))
  (let ((a-value (f a))
        (b-balue (f b)))
    （cond ((and (negative? a-value) (positive? b-value))
            (search f a b))
           ((and (positive? a-value) (negative? b-value))
            (search f b a))
           (else
             (error "Value are not of opposite" a b))))
